"""Sidecar 入口：被 PyInstaller 打成 exe，由 Tauri 以 sidecar 方式拉起。

握手协议（任务书 §4「sidecar 端口握手」）
-----------------------------------------
Tauri 在启动时**不知道**后端会占哪个端口，硬编码 8088 必然和用户已开着的
开发实例冲突。所以：

1. 本脚本用 ``--port 0`` 让操作系统分配一个空闲端口；
2. uvicorn 真正绑定后，把**实际端口**通过 stdout 打印一行::

       FY_SIDECAR_READY <port>

3. Rust 侧读到这一行才创建窗口加载 ``http://127.0.0.1:<port>``。

stdout 会被 PyInstaller 的窗口模式吞掉，所以除了 stdout 还把端口写到
``%APPDATA%/FindYourself/run/port.txt`` 作为第二条通道（Rust 侧两个都读，
先到先用）。这两条都拿不到时 Rust 会**明确报错**并退出，不会退化成
「猜一个端口然后白屏」。

数据与密钥
----------
* SQLite 落在 ``%APPDATA%/FindYourself/data/find-yourself.db``（沿用
  ``run_desktop.py`` 的布局，两条路径看到同一份数据）。
* ``.env`` 首次启动自动生成到 ``%APPDATA%/FindYourself/.env``：随机会话密钥
  与本地口令，**不写死默认值**（P1-14 的教训：可猜测的默认凭据比没有凭据更
  危险）。已有 .env 不覆盖。
"""

from __future__ import annotations

import os
import secrets
import socket
import sys
from pathlib import Path

READY_PREFIX = "FY_SIDECAR_READY"


def data_root() -> Path:
    base = os.environ.get("APPDATA") or os.environ.get("LOCALAPPDATA") or str(Path.home())
    return Path(base) / "FindYourself"


def ensure_env_file(root: Path) -> Path:
    """Create ``.env`` with random secrets on first run. Never overwrite."""
    env_path = root / ".env"
    root.mkdir(parents=True, exist_ok=True)
    if env_path.exists():
        return env_path
    env_path.write_text(
        "# Generated by Find Yourself on first launch. Keep this file private.\n"
        f"FY_SESSION_SECRET={secrets.token_urlsafe(48)}\n"
        f"FY_LOCAL_TOKEN={secrets.token_urlsafe(32)}\n"
        "FY_ENVIRONMENT=local\n"
        "FY_OFFLINE_MODE=1\n"
        "FY_LOCAL_ONLY=1\n",
        encoding="utf-8",
    )
    try:
        env_path.chmod(0o600)
    except OSError:  # pragma: no cover - best effort on non-POSIX
        pass
    return env_path


def free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return int(s.getsockname()[1])


def announce(port: int, run_dir: Path) -> None:
    """Emit the handshake on both channels (stdout + port file)."""
    run_dir.mkdir(parents=True, exist_ok=True)
    try:
        (run_dir / "port.txt").write_text(str(port), encoding="ascii")
    except OSError:
        pass
    print(f"{READY_PREFIX} {port}", flush=True)


def main() -> int:
    root = data_root()
    data_dir = root / "data"
    run_dir = root / "run"
    data_dir.mkdir(parents=True, exist_ok=True)
    run_dir.mkdir(parents=True, exist_ok=True)
    ensure_env_file(root)

    port = free_port()
    static_dir = os.environ.get("FY_STATIC_DIR")
    if not static_dir:
        # PyInstaller --onedir unpacks next to the exe.
        meipass = getattr(sys, "_MEIPASS", None)
        if meipass:
            candidate = Path(meipass) / "web" / "dist"
            if candidate.is_dir():
                static_dir = str(candidate)

    os.environ["FY_ENVIRONMENT"] = "local"
    os.environ["FY_OFFLINE_MODE"] = "1"
    os.environ["FY_LOCAL_ONLY"] = "1"
    os.environ["FY_DATABASE_URL"] = f"sqlite:///{(data_dir / 'find-yourself.db').as_posix()}"
    os.environ["FY_PUBLIC_URL"] = f"http://127.0.0.1:{port}"
    if static_dir:
        os.environ["FY_STATIC_DIR"] = static_dir

    import uvicorn

    from find_yourself.api.app import create_app

    config = uvicorn.Config(
        create_app,
        host="127.0.0.1",
        port=port,
        log_level="warning",
        factory=True,
    )
    server = uvicorn.Server(config)

    import asyncio

    async def _serve() -> None:
        # Announce only once the socket is actually accepting connections, so
        # the Rust side never races the bind.
        server_task = asyncio.create_task(server.serve())
        while not server.started and not server_task.done():
            await asyncio.sleep(0.05)
        if not server.started:
            server_task.cancel()
            raise RuntimeError("backend failed to start")
        announce(server.servers[0].sockets[0].getsockname()[1], run_dir)
        await server_task

    try:
        asyncio.run(_serve())
    except KeyboardInterrupt:
        pass
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
