"""Unified entrypoint and local launcher for Find Yourself (星轨 FY Orbit).

Usage:
    python run.py
    python run.py --port 8000 --no-browser
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import secrets
import subprocess
import sys
import time
import webbrowser

ROOT = Path(__file__).resolve().parent
SRC_DIR = ROOT / "src"
DIST_DIR = ROOT / "web" / "dist"
RUNTIME_DIR = ROOT / ".runtime"
ENV_FILE = ROOT / ".env"

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))
os.environ["PYTHONPATH"] = f"{SRC_DIR}{os.pathsep}{os.environ.get('PYTHONPATH', '')}"


def ensure_env_and_db() -> None:
    RUNTIME_DIR.mkdir(parents=True, exist_ok=True)

    if not ENV_FILE.is_file():
        secret = secrets.token_urlsafe(48)
        content = (
            "# Auto-generated by run.py. Local development only.\n"
            "FY_ENVIRONMENT=local\n"
            "FY_DATABASE_URL=sqlite:///.runtime/find-yourself.db\n"
            f"FY_SESSION_SECRET={secret}\n"
            "FY_LOCAL_TOKEN=dev-token-secret\n"
            "FY_PUBLIC_URL=http://127.0.0.1:8000\n"
        )
        ENV_FILE.write_text(content, encoding="utf-8")
        print("==> Initialized .env with new session secret.")

    # Mount static dist
    if DIST_DIR.is_dir() and (DIST_DIR / "index.html").is_file():
        os.environ["FY_STATIC_DIR"] = str(DIST_DIR)
        print(f"==> Mounted static Web UI: {DIST_DIR}")
    else:
        print("==> Note: web/dist not found. Running API backend only.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Find Yourself (FY Orbit) Unified Launcher")
    parser.add_argument("--host", default="127.0.0.1", help="Host address to bind (default: 127.0.0.1)")
    parser.add_argument("--port", type=int, default=8000, help="Port to bind (default: 8000)")
    parser.add_argument("--no-browser", action="store_true", help="Do not open browser automatically")
    args = parser.parse_args()

    ensure_env_and_db()

    url = f"http://{args.host}:{args.port}"
    print(f"==> Starting FY Orbit on {url}")
    print("==> Press Ctrl+C to terminate.")

    if not args.no_browser:
        def open_tab():
            time.sleep(1.5)
            try:
                webbrowser.open(url)
            except Exception:
                pass
        import threading
        threading.Thread(target=open_tab, daemon=True).start()

    import uvicorn
    from find_yourself.api.app import create_app

    app = create_app()
    uvicorn.run(app, host=args.host, port=args.port, log_level="info")


if __name__ == "__main__":
    main()
