<#
.SYNOPSIS
    One-command launcher for Find Yourself (local, single-port).

.DESCRIPTION
    Idempotent. Safe to run repeatedly.
    Creates .env on first run (random FY_SESSION_SECRET, local dev token),
    initializes the SQLite database, starts uvicorn with the built web UI
    mounted on the SAME port, waits until /health/live returns 200, then
    opens the browser.

    ASCII-only content on purpose: Windows PowerShell 5.1 reads .ps1 as ANSI
    unless a UTF-8 BOM is present. Chinese docs live in README.md instead.

.EXAMPLE
    .\start.ps1
    .\start.ps1 -Port 8000
    .\start.ps1 -Stop
    .\start.ps1 -ResetData
#>
[CmdletBinding()]
param(
    [int]$Port = 8000,
    [string]$Host_ = "127.0.0.1",
    [string]$LocalToken = "dev-token-secret",
    [switch]$Stop,
    [switch]$ResetData,
    [switch]$NoBrowser
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $Root

function Write-Step  { param($m) Write-Host "==> $m" -ForegroundColor Cyan }
function Write-Ok    { param($m) Write-Host "    OK  $m" -ForegroundColor Green }
function Write-Warn2 { param($m) Write-Host "    !!  $m" -ForegroundColor Yellow }
function Write-Err2  { param($m) Write-Host "    XX  $m" -ForegroundColor Red }

# ---------------------------------------------------------------- stop mode
if ($Stop) {
    $conns = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue
    if (-not $conns) {
        Write-Step "Stop: nothing listening on port $Port"
        exit 0
    }
    foreach ($c in $conns) {
        try {
            Stop-Process -Id $c.OwningProcess -Force -ErrorAction Stop
            Write-Ok "stopped pid $($c.OwningProcess) on port $Port"
        } catch {
            Write-Err2 "could not stop pid $($c.OwningProcess): $($_.Exception.Message)"
        }
    }
    exit 0
}

# ---------------------------------------------------- locate the interpreter
$py = Join-Path $Root ".venv\Scripts\python.exe"
if (-not (Test-Path $py)) {
    $fallbackPys = @(
        $env:PYTHON_EXECUTABLE
    )
    foreach ($cand in $fallbackPys) {
        if ($cand -and (Test-Path $cand)) {
            $py = $cand
            break
        }
    }
}
if (-not (Test-Path $py)) {
    $sysPy = Get-Command python -ErrorAction SilentlyContinue
    if ($sysPy) { $py = $sysPy.Source }
}
if (-not (Test-Path $py)) {
    Write-Err2 "No python environment found at .venv or system PATH"
    Write-Host "    Create it first:" -ForegroundColor Yellow
    Write-Host "      py -3.12 -m venv .venv" -ForegroundColor Yellow
    Write-Host "      .venv\Scripts\python.exe -m pip install -e ." -ForegroundColor Yellow
    exit 1
}
Write-Step "Interpreter: $((& $py --version 2>&1) -join ' ')"

# ------------------------------------------------------------- .env upkeep
$envFile = Join-Path $Root ".env"
$needWrite = $false

if (-not (Test-Path $envFile)) {
    Write-Step "First run: creating .env"
    $needWrite = $true
} else {
    $txt = Get-Content $envFile -Raw -ErrorAction SilentlyContinue
    if ($txt -notmatch '(?m)^\s*FY_SESSION_SECRET\s*=\s*\S{32,}') { $needWrite = $true }
    if ($txt -notmatch "(?m)^\s*FY_LOCAL_TOKEN\s*=\s*\S+")          { $needWrite = $true }
    if ($txt -notmatch "(?m)^\s*FY_DATABASE_URL\s*=\s*\S+")        { $needWrite = $true }
}

if ($needWrite) {
    $secret = (& $py -c "import secrets;print(secrets.token_urlsafe(48))").Trim()
    if ([string]::IsNullOrWhiteSpace($secret)) {
        $secret = [guid]::NewGuid().ToString("N") + [guid]::NewGuid().ToString("N")
    }
    $lines = @(
        "# Auto-generated by start.ps1. Local development only. Never commit.",
        "FY_ENVIRONMENT=local",
        "FY_DATABASE_URL=sqlite:///$('')",   # replaced below
        "FY_SESSION_SECRET=$secret",
        "FY_LOCAL_TOKEN=$LocalToken",
        "FY_PUBLIC_URL=http://${Host_}:$Port",
        "FY_MODEL_API_KEY=",
        "FY_MODEL_BASE_URL="
    )
    $lines[2] = "FY_DATABASE_URL=sqlite:///.runtime/find-yourself.db"
    Set-Content -Path $envFile -Value $lines -Encoding UTF8
    Write-Ok ".env written (session secret generated)"
} else {
    Write-Ok ".env already usable"
}

# --------------------------------------------------- already running? (idempotent)
$base = "http://${Host_}:$Port"
$live = $null
try { $live = Invoke-WebRequest -Uri "$base/health/live" -TimeoutSec 2 -UseBasicParsing } catch { }
if ($live -and $live.StatusCode -eq 200) {
    Write-Step "Already running at $base"
    Write-Ok "health/live -> 200"
    if (-not $NoBrowser) { Start-Process $base }
    exit 0
}

# --------------------------------------------------------------- port check
$busy = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue
if ($busy) {
    Write-Err2 "Port $Port is in use by another process (pid $($busy[0].OwningProcess))."
    Write-Host "    Pick another port:  .\start.ps1 -Port 8010" -ForegroundColor Yellow
    exit 1
}

# ------------------------------------------------------------ reset request
if ($ResetData) {
    # SQLite 以 WAL 模式运行（见 db/session.py 的 PRAGMA journal_mode=WAL），
    # 因此数据库实际由三个文件组成：.db + -wal + -shm。
    # 只删 .db 会留下未合并的 WAL 与共享内存文件 —— 下次启动时 SQLite 可能
    # 把旧事务重放到「已重置」的库上（状态残留），排查时表现为「重置了但数据还在」。
    # 三个一并删，缺哪个报哪个。
    $dbFiles = @(
        (Join-Path $Root ".runtime\find-yourself.db"),
        (Join-Path $Root ".runtime\find-yourself.db-wal"),
        (Join-Path $Root ".runtime\find-yourself.db-shm")
    )
    $removed = 0
    foreach ($f in $dbFiles) {
        if (Test-Path $f) {
            Remove-Item $f -Force
            Write-Ok "removed $f"
            $removed++
        }
    }
    if ($removed -gt 0) {
        Write-Ok "data reset complete ($removed file(s) removed, incl. WAL/SHM)"
    } else {
        Write-Ok "no existing database to reset"
    }
}

# -------------------------------------------------- runtime dirs / static UI
New-Item -ItemType Directory -Force -Path (Join-Path $Root ".runtime") | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $Root ".runtime\artifacts") | Out-Null

$dist = Join-Path $Root "web\dist"
if (Test-Path (Join-Path $dist "index.html")) {
    Write-Ok "web UI present (web\dist) - serving from the same port"
    $env:FY_STATIC_DIR = $dist
} else {
    Write-Warn2 "web\dist\index.html not found - API only, no UI."
    Write-Host "    Build it with:  cd web; npm install; npm run build" -ForegroundColor Yellow
}

# ------------------------------------------------------------------- launch
$logDir = Join-Path $Root ".runtime"
$outLog = Join-Path $logDir "server.out.log"
$errLog = Join-Path $logDir "server.err.log"

$env:FY_ENVIRONMENT = "local"
$env:FY_LOCAL_TOKEN = $LocalToken
$env:FY_PUBLIC_URL = $base

Write-Step "Starting uvicorn on $base"
$proc = Start-Process -FilePath $py `
    -ArgumentList @("-m", "uvicorn", "find_yourself.api.app:create_app", "--factory",
                    "--host", $Host_, "--port", "$Port") `
    -WorkingDirectory $Root `
    -RedirectStandardOutput $outLog `
    -RedirectStandardError $errLog `
    -WindowStyle Hidden `
    -PassThru

# --------------------------------------------------------- wait until ready
$ready = $false
$deadline = (Get-Date).AddSeconds(75)
while ((Get-Date) -lt $deadline) {
    if ($proc.HasExited) { break }
    try {
        $r = Invoke-WebRequest -Uri "$base/health/live" -TimeoutSec 2 -UseBasicParsing
        if ($r.StatusCode -eq 200) { $ready = $true; break }
    } catch { }
    Start-Sleep -Milliseconds 700
}

if (-not $ready) {
    Write-Err2 "Server did not become healthy in time."
    if ($proc.HasExited) { Write-Host "    Process exited with code $($proc.ExitCode)." -ForegroundColor Red }
    Write-Host "    ---- stderr tail ----" -ForegroundColor Red
    if (Test-Path $errLog) { Get-Content $errLog -Tail 25 | ForEach-Object { Write-Host "    $_" -ForegroundColor DarkGray } }
    Write-Host "    -------------------" -ForegroundColor Red
    exit 1
}

Write-Ok "health/live -> 200 (pid $($proc.Id))"

# ------------------------------------------------------------------- report
try {
    $api = Invoke-WebRequest -Uri "$base/openapi.json" -TimeoutSec 5 -UseBasicParsing
    $paths = ($api.Content | ConvertFrom-Json).paths.PSObject.Properties.Name.Count
    Write-Ok "API mounted - $paths endpoints under /api"
} catch {
    Write-Warn2 "could not read openapi.json: $($_.Exception.Message)"
}

Write-Host ""
Write-Host "  Find Yourself is running." -ForegroundColor Green
Write-Host "  URL           : $base" -ForegroundColor Green
Write-Host "  API docs      : $base/docs" -ForegroundColor Green
Write-Host "  Local token   : $LocalToken" -ForegroundColor Green
Write-Host "  Database      : .runtime\find-yourself.db" -ForegroundColor Green
Write-Host "  Logs          : .runtime\server.out.log / server.err.log" -ForegroundColor Green
Write-Host ""
Write-Host "  First run has no data. Load a demo subject with:" -ForegroundColor Yellow
Write-Host "    .venv\Scripts\python.exe scripts\seed_demo_data.py" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Stop with:  .\start.ps1 -Stop" -ForegroundColor DarkGray
Write-Host ""

if (-not $NoBrowser) {
    Start-Sleep -Milliseconds 600
    Start-Process $base
    Write-Ok "browser opened"
}

exit 0
