name: Release Docker

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    name: Build & Publish Production Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: find-yourself/app:${{ github.ref_name }},find-yourself/app:latest
